# Generated by Django 4.0.2 on 2022-03-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0003_myuser_description_myuser_number_of_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='favorite_movies',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='hometown',
            field=models.TextField(default=''),
        ),
    ]
