# Generated by Django 4.0.2 on 2022-03-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0004_remove_event_description_remove_event_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='number_of_events',
        ),
    ]
