# Generated by Django 4.0.2 on 2022-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0005_remove_myuser_number_of_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Event Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Date'),
        ),
    ]
