# Generated by Django 4.0.2 on 2022-03-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0006_event_event_time_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, default='2022-03-29', null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='14:36', null=True, verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('In Person', 'In Person'), ('Virtual', 'Virtual')], default='In Person', max_length=100),
        ),
    ]
