# Generated by Django 4.0.2 on 2022-03-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0007_event_event_post_date'),
        ('watchparty', '0008_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
    ]
