# Generated by Django 4.0.2 on 2022-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0009_merge_20220329_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='15:04', null=True, verbose_name='Event Time'),
        ),
    ]
