# Generated by Django 4.0.2 on 2022-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0012_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_edit_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Edit Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_post_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='16:51', null=True, verbose_name='Event Time'),
        ),
    ]
