# Generated by Django 4.0.2 on 2022-04-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0013_event_event_edit_date_alter_event_event_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='16:59', null=True, verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('IN_PERSON', 'In Person'), ('ONLINE', 'Online')], max_length=100),
        ),
    ]
