# Generated by Django 4.0.2 on 2022-04-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0016_alter_event_event_date_alter_event_event_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='14:03', null=True, verbose_name='Event Time'),
        ),
    ]
