# Generated by Django 4.0.2 on 2022-04-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0017_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_RSVP',
            field=models.ManyToManyField(related_name='RSVP', to='watchparty.MyUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='15:00', null=True, verbose_name='Event Time'),
        ),
    ]
