# Generated by Django 4.0.2 on 2022-04-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0022_alter_event_event_rsvp_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='15:46', null=True, verbose_name='Event Time'),
        ),
    ]
