# Generated by Django 4.0.2 on 2022-04-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0026_alter_event_event_rsvp_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='18:07', null=True, verbose_name='Event Time'),
        ),
    ]
