# Generated by Django 4.0.2 on 2022-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0028_remove_myuser_name_alter_event_event_rsvp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='13:44', null=True, verbose_name='Event Time'),
        ),
    ]
