# Generated by Django 4.0.2 on 2022-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0032_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, default='2022-04-15', null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='13:13', null=True, verbose_name='Event Time'),
        ),
    ]
