# Generated by Django 4.0.2 on 2022-04-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchparty', '0034_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='16:21', null=True, verbose_name='Event Time'),
        ),
    ]
