# Generated by Django 4.0.2 on 2022-04-24 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchparty', '0039_alter_event_event_date_alter_event_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='number_of_friends',
        ),
        migrations.AddField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(related_name='Friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default='19:07', null=True, verbose_name='Event Time'),
        ),
    ]
